config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :books
  resources :bookings
  resources :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    include BookVisible

    has_many :bookings
    has_many :users, through: :bookings
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :book
    belongs_to :user

    before_create :add_borrow_date
    after_save :update_book_status
    before_update :update_book_status, if: :due_date_empty?

    # add default booking date
    private
      def add_borrow_date
        self.out_date = DateTime.current()
      end

    # change book status
    private
      def update_book_status
        book = Book.find_by(id: book_id)
        if book.present?
            book.update(status:  'booked')
        end
      end

    private
      def update_book_status
        book = Book.find_by(id: book_id)
        if book.present?
            book.update(status:  'in_stock')
        end
      end
      
    private
      def due_date_empty?
        !self.due_date.present?
      end
end

app/models/user.rb
class User < ApplicationRecord
    include UserVisible

    has_many :bookings
    has_many :books, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all

    # p @bookings.book

    @bookings.each do |book|
      
    end

  end

  def show
    @booking = Booking.find(params[:id])

    @book = Book.find(@booking.book_id)
    @user = User.find(@booking.user_id)
  end

  def new
    @book = Book.find(params[:id])
    @users = User.all
    
    @booking = Booking.new
  end

  def create
    p booking_params
    @booking = Booking.new(booking_params)
    
    if @booking.save
      redirect_to @booking
    else
      render :new
    end
  end
  
  def edit
    @booking = Booking.find(params[:id])

    if !@booking.book_id.present?
      redirect_to bookings_url
    else
      @book = Book.find(@booking.book_id)
    end
  end

  def update
    @booking = Booking.find(params[:id])

    if @booking.update(booking_params)
      redirect_to @booking
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to bookings_path, status: :see_other
  end

  private
    def booking_params
      params.require(:booking).permit(:out_date, :due_date, :book_id, :user_id)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    
    if @book.save
      redirect_to @book
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @book = Book.find(params[:id])
  end

  def update
    p book_params

    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path, status: :see_other
  end

  private
    def book_params
      params.require(:book).permit(:name, :description, :status)
    end
end

app/controllers/concerns/book_visible.rb
module BookVisible
    extend ActiveSupport::Concern

    VALID_STATUSES = ['in_stock', 'booked', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    class_methods do
        def public_count
          where(status: ['in_stock', 'booked']).count
        end
    end

    def archived?
      status == 'archived'
    end
end

app/controllers/concerns/user_visible.rb
module UserVisible
    extend ActiveSupport::Concern

    VALID_STATUSES = ['active', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    class_methods do
        def public_count
          where(status: 'active').count
        end
    end

    def archived?
      status == 'archived'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path, status: :see_other
  end

  private
    def user_params
      params.require(:user).permit(:name, :user_name, :password, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/_form.html.erb
<%= form_with model: @booking do |form| %>
  <%= form.select :user_id, options_from_collection_for_select(@users, "id", "name")%>
  <%= form.hidden_field :book_id, value: @book.id %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<div class="text-xl">Return Book - <%= @book.name %></div>

<%= form_with model: @booking do |form| %>
    <div>
        <%= form.hidden_field :due_date, value: DateTime.current() %>
    </div>
    <%= form.submit :Submit, class: "rounded bg-stone-300 p-4 cursor-pointer" %>
<% end %>

<%= link_to "Back to booking list", bookings_path %>

app/views/bookings/index.html.erb
<div class="text-xl">Bookings list</div>

<div>
    <table>
        <thead>
            <tr>
                <th>Borrow Date</th>
                <th>Return Date</th>
                <th>Book Name</th>
                <th>Borrower Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <% @bookings.each do |booking| %>
            <tr>
                <td><%= booking.out_date %></td>
                <td><%= booking.due_date %></td>
                <td><%= booking.book_id %></td>
                <td><%= booking.user_id %></td>
                <% if !booking.due_date.present? %>
                    <td>
                        <%= link_to edit_booking_path(booking) do %>
                            <div class="rounded bg-stone-300 p-4 cursor-pointer">Return book</div>
                        <% end %>
                    </td>
                <% end %>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/bookings/new.html.erb
this is new booking
<h1><%= @book.name %></h1>
<div>
<% if @book.status == 'in_stock' %>
    <%= render "form", booking: @booking, users: @users, book: @book %>
<% end %>

</div>

app/views/bookings/show.html.erb
<div class="text-5xl"><%= @book.name %></div>

Borrower Name: <%= @user.name %><br />
Borrow Date: <%= @booking.out_date %><br />
Return Date: <%= @booking.due_date %><br />
Current Book Status: <%= @book.status %><br />

<%= link_to "Back to booking list", bookings_path %>

app/views/books/_form.html.erb
<%= form_with model: book do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% book.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :description %><br>
      <%= form.text_area :description %><br>
      <% book.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :status %><br>
      <%= form.select :status, BookVisible::VALID_STATUSES, selected: book.status || 'in_stock' %>
    </div>

    <div>
      <%= form.submit %>
    </div>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render "form", book: @book %>

<%= link_to "Back to book list", books_path %>

app/views/books/index.html.erb
<h1>Book list</h1>

<ul>
  <% @books.each do |book| %>
    <% unless book.archived? %>
      <li>
        <%= link_to book.name, book %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "Create new book", new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render "form", book: @book %>

app/views/books/show.html.erb
<h1><%= @book.name %></h1>

<p><%= @book.description %></p>

Status: <%= @book.status %>

<% if @book.status == 'in_stock' %>
  <%= link_to "Borrow Book", new_booking_path(:id => @book.id) %>
<% end %>

<ul>
  <li><%= link_to "Edit", edit_book_path(@book) %></li>
  <li><%= link_to "Destroy", book_path(@book), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
</ul>

<%= link_to "Back to book list", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% user.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :user_name %><br>
      <%= form.text_field :user_name %>
      <% user.errors.full_messages_for(:user_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :password %><br>
      <%= form.password_field :password %><br>
      <% user.errors.full_messages_for(:password).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :status %><br>
      <%= form.select :status, UserVisible::VALID_STATUSES, selected: user.status || 'in_stock' %>
    </div>

    <div>
      <%= form.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form", user: @user %>

<%= link_to "Back to user list", users_path %>

app/views/users/index.html.erb
<h1>User list</h1>

<ul>
  <% @users.each do |user| %>
    <% unless user.archived? %>
      <li>
        <%= link_to user.name, user %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "Create new user", new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

Status: <%= @user.status %>

<ul>
  <li><%= link_to "Edit", edit_user_path(@user) %></li>
  <li><%= link_to "Destroy", user_path(@user), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
</ul>

<%= link_to "Back to user list", users_path %>